### ISSUE TITLE
Good Source addition

### ISSUE THREAD

**Issue by AwesomeGamerAW** [K3vinb5/Unyo#11]
Can you try and add Hikari ? i have the apk for the aniyomi extension if you need it

thanks a lot :D
/
/

**Comment by K3vinb5** [comment]
Hi, so I added Hikari and it works, however it seems my player doesn't support  its streams, whatever's the case I currently don't support multiple subtitles (working on it) if you have other suggestions please open another issue I'm happy to receibe any kind of input! Thank you :smile:!
