### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by Zervinox** [K3vinb5/Unyo#12]
I see that it supports MacOS and that it has code for MacOS but I do not see the download for it. Am I missing something?

**Comment by Zervinox** [comment]
All good dude no worries haha I understand things take time I just wanted to make sure I wasn't missing something. I'll keep an eye out for updates. I understand these projects are hobbies/fun things people are trying to do you have other things. It looks awesome though!

**Comment by K3vinb5** [comment]
Hi, my girdriend tested the new version for me, it works... kinda, it has 2 major bugs, fullscreen doesn't work, and pressing back to leave the anime screen causes a crash, I'll try to address this issues, but it is usable right now if you want to check it out :D
