### ISSUE TITLE
Infinite load on launch

### ISSUE THREAD

**Issue by Marcus0108** [K3vinb5/Unyo#13]
I was able to use the program once on Linux, specifically PopOS 22.04, by downloading the Zip package. After closing the program and restarting my PC, I now can't get past the loading screen. I've done a wipe of everything in regards to Unyo, and retried booting it up again with no change.

When starting Unyo from the terminal I get the following output, accompanied by the infinite loading animation shown when the program boots up.

```
0.29.0 (git 0a3bd27) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux 4KB x86_64; glibc2.24/2.35 libc++190000; Clang19.0.0 (++20240721042146+d69eb7b7ffb3-1~exp1~20240721042318.1816); 12:06:18 Jul 21 2024
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("avatar")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      getUserAvatarImageUrl (package:unyo/api/anilist_api_anime.dart:324)
<asynchronous suspension>
#3      _HomeScreenState.getUserInfo (package:unyo/screens/home_screen.dart:135)
<asynchronous suspension>


```

Let me know if you need anything more from me, or need me to test something.

**Comment by K3vinb5** [comment]
Hi, thanks for your feedback, damn I wished everyone was like you giving me the error log and everything, I will release a new version in the next hours, I'll see why that error is happening and get to you in a bit. :D

**Comment by K3vinb5** [comment]
I think it's done, I can't reproduce the issue, so you'll let me know on the next version if it's solved xD, hopefully yes.

**Comment by Marcus0108** [comment]
Sounds good, I'll let you know if anything changes with the next version

**Comment by K3vinb5** [comment]
The next version didn't release yet because of a problem in mac, should be done today, sorry for the delay

**Comment by Marcus0108** [comment]
No worries, I'm in no rush and did also see you tried a couple of times yesterday due to the MacOS issues

**Comment by Marcus0108** [comment]
Just tested with release 0.6.0, and got the below errors

```
0.29.0 (git 0a3bd27) - Multimedia Development Kit. Copyright (c) 2016-2024 WangBin(QtAV author) <wbsecg1 at gmail.com>
Build for: Linux 4KB x86_64; glibc2.24/2.35 libc++190000; Clang19.0.0 (++20240721042146+d69eb7b7ffb3-1~exp1~20240721042318.1816); 12:06:18 Jul 21 2024
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("lists")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38)
#1      _objectNoSuchMethod (dart:core-patch/object_patch.dart:85)
#2      getUserAnimeLists (package:unyo/api/anilist_api_anime.dart:430)
<asynchronous suspension>
#3      _HomeScreenState.getUserInfo (package:unyo/screens/home_screen.dart:138)
<asynchronous suspension>
```

**Comment by K3vinb5** [comment]
That is really weird, what I advise you to do is to your %appdata% and inside com.example you'll find a folder called unyo, just delete that folder.

**Comment by K3vinb5** [comment]
Sorry, just remembered you are on linux, go to /home/{your_user}/.local/share/ and delete com.example.unyo, and try and launch the app and login again, tell me how it went :D .

**Comment by Marcus0108** [comment]
Just did that and tested release 0.6.0, and got the following error, after succeeding in getting an access token from the Anilist API. 
``` 
ERROR - 2024-07-26 00:42:37.937300
Asynchronous error
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("lists")
dart:core                                    _objectNoSuchMethod
package:unyo/api/anilist_api_anime.dart 430  getUserAnimeLists
```

I've additionally tried removing the app connection from the Anilist website before deleting the com.example.unyo folder, and it results in the same error as above.

If I attempt to connect with 0.5.0 release version after deleting the folder, then I get the below error
```
ERROR - 2024-07-26 00:47:05.920432
Asynchronous error
NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("avatar")
dart:core                                    _objectNoSuchMethod
package:unyo/api/anilist_api_anime.dart 324  getUserAvatarImageUrl
```

**Comment by K3vinb5** [comment]
D: 
I say what do you think you add me on discord and we could try and debug that together tomorrow, you're the first with this problem but every problem has a solution :)
My id on discord is kiwib5
