### ISSUE TITLE
Can't use without anilist account ?

### ISSUE THREAD

**Issue by Anazark** [K3vinb5/Unyo#17]
Hello, I just tried Unyo (thanks for the portable version, always appreciated) but I can't seem to get past the first screen asking me to connect to an Anilist account
But I don't have one and I don't want one. Is there no way to use the program without one ? That would be a shame, Unyo looks great I would love to use it

Thanks in advance !

**Comment by K3vinb5** [comment]
Hi, I was on vacations for the last 2 weeks so the project has been a bit dead, but it will return right away, yeah sure it will possible to use the app without an anilist account in the future, i had it planed for recently but will make it a priority for you :D. I'll close the issue once it gets added, I'll start coding right away :).

**Comment by Anazark** [comment]
Oh that's so nice of you, thanks a lot ! But don't worry i'm not in any hurry so take all your time
And enjoy your vacations ! 

PS : please if you could send a msg here whenever the update is done so I know it would be great

Thanks again 👋

**Comment by K3vinb5** [comment]
Hi, It's done! Hope you like it!

**Comment by Anazark** [comment]
thank you so much !
