### ISSUE TITLE
cant Install Extensions

### ISSUE THREAD

**Issue by simploita78** [K3vinb5/Unyo#18]
I am not unable to install extenion i mean the extesnion page is visible but when  i click download button and refresh the app still cant play any anime or read any manga**
![image](https://github.com/user-attachments/assets/c00f2c9e-e080-489b-80e0-f6ee8642fe26)
**

**Comment by simploita78** [comment]
i more thing - i have installed all of the extensions i seen

**Comment by K3vinb5** [comment]
Hi, so srry to hear that, you could use remote extensions for the time being.
I'll ask you some questions, what is your operating system?
And could you show me a print of what appears in the console in the local extensions screen (make sure to scroll down).

**Comment by simploita78** [comment]
https://github.com/user-attachments/assets/63fd1292-66d5-4ee3-9b4b-7cd13b750957

actually now the manga section is working but Anime still not i have uploaded a video

**Comment by simploita78** [comment]
![image](https://github.com/user-attachments/assets/9a73e5cb-969a-4696-bd52-ea8233f21393)

a quick look to my setting

**Comment by K3vinb5** [comment]
Alright, what I meant before whas a screenshot of the "Local Extensions" screen, also, in settings, you can turn off local extensions and that fixes the issue (You will be using remote extensions instead).

**Comment by simploita78** [comment]
ohh thanks for help but can you tell me how to use remote extension a quick guide yk. also i am waiting for new release. thanks again for the help

**Comment by K3vinb5** [comment]
to use remote extensions turn off the last option in the settings.
