### ISSUE TITLE
the video player keeps crashing

### ISSUE THREAD

**Issue by SKCoder2** [K3vinb5/Unyo#19]
When i select the quality or server of the anime video like gogostream or vidstream it keeps closing the whole program.

**To Reproduce**
1. Go to any anime in the anime page 
2. Click on any episode of an anime
3. Select any quality the app will crash

**Expected behavior**
After the clicking on any quality it should run the video,

**Screenshots**
![Screenshot 2024-08-28 233424](https://github.com/user-attachments/assets/1f5176db-19e4-40c8-8d1e-e0254c7d0d08)
![Screenshot 2024-08-28 233424](https://github.com/user-attachments/assets/0fc1efe6-c7ad-4463-a229-948a76cff5b7)

![Screenshot 2024-08-28 233347](https://github.com/user-attachments/assets/84abc3c8-3000-4606-90b3-e5e869a6036b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 23H2 X64 based

**Comment by K3vinb5** [comment]
Hi, I'll be honest with you, it's not the first time people have complained about the video crashing, and what I learned is that it seems to be quite random unfortunately, some people have it, other don't.
From what I could grasp until now it seems to only happen on windows and to a small proportion of people, I'll se what I can do and answer you in a couple weeks max, I'm sorry for the inconvenience

**Comment by K3vinb5** [comment]
Hi, if you haven't installed Visual C++ Redistributable for Visual Studio 2015-2022 you could try that, [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) is the link to microsoft website, select the correct one for your OS (x86 for x86-32bit, x64 for x86-64bit and arm for arm)

**Comment by SKCoder2** [comment]
Thanks for the quick response appreciate it

**Comment by SKCoder2** [comment]
> Hi, if you haven't installed Visual C++ Redistributable for Visual Studio 2015-2022 you could try that, [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022) is the link to microsoft website, select the correct one for your OS (x86 for x86-32bit, x64 for x86-64bit and arm for arm)

thanks bro it worked

**Comment by SKCoder2** [comment]
after installing visual c++ it worked
