### ISSUE TITLE
Window Scaling

### ISSUE THREAD

**Issue by TitanDeploy** [K3vinb5/Unyo#25]
Really enjoying the app so far. One thing I think could use some tweaking is the window scaling. For context, I'm on a 13" laptop and the Windows display scaling in settings is set to 150%. If I go any lower, the taskbar and other things become much too small. However, when I use the Unyo app, the window is stretched slightly beyond the confines of my display. For example, I can't see the close bottom at the top-right of the window. If the window could dynamically adjust to the display size, that would be absolutely awesome.

**Comment by K3vinb5** [comment]
Hi!, thanks for the feedback, I can decrease the minimum window size.
