### ISSUE TITLE
BUG/ISSUE just stopped working

### ISSUE THREAD

**Issue by RealFoxass** [K3vinb5/Unyo#26]
I am aware that local extension is not working on windows at this current moment but now even when I have local extension off it keep thinking I have it on not letting me use the application all together, PLEASE FIX!
![Screenshot 2024-09-15 053339](https://github.com/user-attachments/assets/c247a69f-54ab-46dd-82f6-aa71b39e07ae)
![Screenshot 2024-09-15 053448](https://github.com/user-attachments/assets/8b029515-d91d-4cbb-903f-279cec4126b2)

**Comment by Bashame** [comment]
The problem most likely is that the server broke,thats what happened last time

**Comment by K3vinb5** [comment]
Yeah, the server went down, I have to do a scheduler to restart it every other day or every day, I will restart it right away, I was away this weekend and didn't see this earlier, btw, that error message will display the proper error message next version, sorry for the incovenience and thank's for using the app :D
