### ISSUE TITLE
BUG/ISSUE

### ISSUE THREAD

**Issue by billasur** [K3vinb5/Unyo#30]
![image](https://github.com/user-attachments/assets/7ce6497c-80fc-4edc-a41a-a5f23e474805)
thats all

**Comment by cyber532** [comment]
yeah i got the same error

**Comment by cyber532** [comment]
anyone know how to fix it.

**Comment by K3vinb5** [comment]
Hiii guys, thank you for reporting the issue, everything should be back to normal now, sorry for the incovenience :D

**Comment by cyber532** [comment]
thx so much!!
