### ISSUE TITLE
Unyo source error

### ISSUE THREAD

**Issue by cyber532** [K3vinb5/Unyo#31]
![Screenshot from 2024-09-25 22-56-26](https://github.com/user-attachments/assets/67d87441-b74c-498c-82c1-2d90ff9a2fef)

**Comment by cyber532** [comment]
so i was watching normally when all of a sudden while moving to the next ep this happened.

**Comment by cyber532** [comment]
One more important thing i forgot to mention,i tried using local sources but it still did not work.

**Comment by cyber532** [comment]
I am closing this issue because i checked today morning,and i found it fixed.

**Comment by K3vinb5** [comment]
Hi, yeah sry for taking too long to answer, that type of error is usually the website fault, the best thong to do is just use another extension, that's the great thing about this app is that you can always just change extensions.

**Comment by cyber532** [comment]
Thanks so much for the reply man.
Sorry for replying late.

Sent from Yahoo Mail on Android 
 
  On Fri, 27 Sep 2024 at 5:09 AM, Kevin Rodrigues ***@***.***> wrote:   


Hi, yeah sry for taking too long to answer, that type of error is usually the website fault, the best thong to do is just use another extension, that's the great thing about this app is that you can always just change extensions.
