### ISSUE TITLE
server down

### ISSUE THREAD

**Issue by cyber532** [K3vinb5/Unyo#32]
![image](https://github.com/user-attachments/assets/0ff2f7e9-c73d-4bb5-8739-eaf2cccb3ea0)

Thats all.

opened unyo to watch today got this error.

**Comment by K3vinb5** [comment]
Solved, sorry, still working on a solution, it's been hard this couple of weeks, I just started a new job and my masters, next weeks I should eventually get my shit together and manage to have some more free time
