### ISSUE TITLE
BUG/ISSUE: Unyo is not opening on my pc

### ISSUE THREAD

**Issue by IkramHussainSiyam** [K3vinb5/Unyo#34]
**Describe the bug**
I installed Unyo and opened but it stuck in loading screen forever it won't open. The home screen and nothing shows.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Unyo Latest Version

**Screenshots**
![{C2A424CD-DD4B-4350-8F9B-E94EB1D2C8E0}](https://github.com/user-attachments/assets/d8b1f3e0-85d6-4863-8e39-89482b6ac15c)

**Comment by K3vinb5** [comment]
Hi, could you open it through the console to show me the logs? Another question is weather you logged in with anilist, and if you did do you have your anilist profile set to public or semi-public (More information about this in the readme).

Please share your progress with me so I can help you solve this.

**Comment by K3vinb5** [comment]
Hi!, Could you try to delete the folder at: %appdata%\k3vinb5.app and see what you get?

**Comment by IkramHussainSiyam** [comment]
> Hi!, Could you try to delete the folder at: %appdata%\k3vinb5.app and see what you get?

It Worked Thanks

**Comment by K3vinb5** [comment]
Hi, I'm glad it worked, I'll close the issue now, jope you enjoy using the app, more updates are coming soon, probably to do with extensions and tooling for other people to develop extensions
