### ISSUE TITLE
KAA doesn't have audio

### ISSUE THREAD

**Issue by anotherduckling** [K3vinb5/Unyo#4]
KAA's own server was working fine in 0.4.9. But Bilibili server didnt have audio. In 0.5.0, both dont have audio.

**Comment by K3vinb5** [comment]
I'm aware of the issue and working on a fix, basically KAA audio source is separate, will be fixed eventually, I'll let you know when it's fixed and then I'll close the issue

**Comment by K3vinb5** [comment]
The fix should release later today :)

**Comment by K3vinb5** [comment]
The fix just released, some sources in kaa still don't have subtitles, but the majority of the episodes will have that does
