### ISSUE TITLE
Shows nothing

### ISSUE THREAD

**Issue by cyber532** [K3vinb5/Unyo#48]
hi so i wanted to watch a new anime but when i went to the anime menu there was nothing.So i ran unyo from my terminal and it showed this:
![image](https://github.com/user-attachments/assets/b05c8bf3-292d-4025-afaf-b7b827c7a10b)

pls fix this

thanks in advance!!

**Comment by cyber532** [comment]
Oh i and one more thind the ones i had saved in my current list sill works

**Comment by cyber532** [comment]
sorrry for some reason it just fixed itself so i am closing the issue

**Comment by K3vinb5** [comment]
Hi, anilist was down that day xD. It fixed itself because their api went live again :D. If something like this happens again don't mind opening an issue :D.
