### ISSUE TITLE
BUG/ISSUE

### ISSUE THREAD

**Issue by DToila** [K3vinb5/Unyo#49]
Buffering problem in almost every anime, it gets worst the more I watch, I have a stable internet connection,  and I have tried other apps and seem to function smoothly.

**Expected behavior**
A smooth stream of any episode without any unwanted stoppages throughout the whole episode 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 23H2

**Additional context**
It could be due to my network connection but I'm 90% sure that it isn't, because as I said , I used other apps on my PC and the episodes played smoothly, but I might also be wrong

**Comment by K3vinb5** [comment]
Hi, noone has ever experienced that, so my assumption is that it is either some vpn or service you have on the background interrupting the stream or a bad internet connection, I'd advise you to please try run the app on the same pc on another internet connection.
