### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by chitrakshbotwala** [K3vinb5/Unyo#5]
I am the web developer guy in the dantotsu server ( CM ) i guess you wouldve seen me once and if you havent its ok lmao , so i wanted to contribute to the project and wanted to help you guys dm me if you wanna work or if we could do this along with dantotsu maybe as a dantotsu pc version ( we just close down the website then and focus on pc dantotsu and android dantotsu )

**Comment by GABIlopez** [comment]
Anime apk

**Comment by sneazy-ibo** [comment]
sup I am an developer of the Dantotsu mobile app and also just found out about your project, I would also really like to contribute to the app :)
