### ISSUE TITLE
BUG/ISSUE

### ISSUE THREAD

**Issue by billasur** [K3vinb5/Unyo#52]
server is down it is saying 
![image](https://github.com/user-attachments/assets/4480809e-e668-42f0-84ca-a64d40ae32e3)

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. 24.04]

**Additional context**

**Comment by K3vinb5** [comment]
Server back up :). I'm sorry for the inconenience and have a look at local extensions, still a bit bugy but in the future when they're more stable there won't be a server.
