### ISSUE TITLE
App force close

### ISSUE THREAD

**Issue by Drac1652** [K3vinb5/Unyo#7]
I don't know why but the app force close every time i select a resolution to play the anime

**Comment by K3vinb5** [comment]
Hi, so it crashes when you go into the video right?

What is your os?
Have you been able to get into the video screen at all or does it always crash?

**Comment by Drac1652** [comment]
> Hi, so it crashes when you go into the video right?
> 
> What is your os? Have you been able to get into the video screen at all or does it always crash?

My OS is windows 11.
And No, just after i select a video Quality to play it kinda stucks a bit and then crashes and this is for all servers

**Comment by K3vinb5** [comment]
Hi, I will look into this, I don't use windows myself so I wasn't aware that some people were experiencing that.
I will get back to you on here in a week or so. :smiley:

**Comment by K3vinb5** [comment]
Hi, so I still have no idea what is causing the issue, I will try and update the package of the video player maybe that will solve the issue, other people in windows are experiecing weird issues, besides crashes weird bugs on the video, hopefully with time and the development of the fvp video player package (you can check their github) it will get better, right now works great for some and not so great for others
